{% set name = "yacs" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rbgirshick/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f1db3a1e204f840b7e659eaf9828add121af6a1b219d72ea97a5afe7e29e0f25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - pyyaml 6.0.2
  run:
    - python
    - pyyaml

test:
  source_files:
    - example
  imports:
    - yacs
  commands:
    - pip check
    - python ${SP_DIR}/yacs/tests.py  # [unix]
    - pytest -v %SP_DIR%\\yacs\\tests  # [win]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/rbgirshick/yacs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'YACS -- Yet Another Configuration System'
  description: |
    YACS -- Yet Another Configuration System
    YACS was created as a lightweight library to define and manage system configurations, such as those commonly found in software designed for scientific experimentation. 
  doc_url: https://github.com/rbgirshick/yacs
  dev_url: https://github.com/rbgirshick/yacs

extra:
  recipe-maintainers:
    - hadim
